### ISSUE TITLE
Why ARGLEN is so small?

### ISSUE THREAD

**Issue by yegortimoschenko** [snimmagadda/pop3d#7]
I've just tried using using pop3d with 50 character password, and apparently it failed:

```
PASS  (*** 50 bytes hidden ***)
-ERR args required or too long
```

Why `ARGLEN` is just 40 bytes at [pop3d.h#L25](https://github.com/snimmagadda/pop3d/blob/0a132f05d8f0a74ba85a4cc59b755bc20a2a34a8/pop3d.h#L25)?

**Comment by snimmagadda** [comment]
Since RFC 1939 specifies "Each argument may be up to 40 characters long". I think it can be bumped up.

**Comment by yegortimoschenko** [comment]
I've missed that while reading the spec. On second thought, 40 bytes should be enough.
Sorry for bothering you!
